### ISSUE TITLE
pcp decrypt in streaming mode needs a lot of memory?

### ISSUE THREAD

**Issue by Intensity** [TLINDEN/pcp#10]
Maybe I've misunderstood but can you please clarify if there are memory limitations involved with decrypting from a stream (stdin) to stdout?  This is on Debian 7 x86_64.  I was able to write from a file to a stream just fine:

  $ cat bigfile | pcp1 --verbose  --sign  --encrypt --add-myself | split -a4 -b1G - /mnt/out.x

But when I try to decrypt this, just to check the md5sum:

  $ cat /mnt/out.x* | pcp1 --verbose --decrypt | md5sum

I get:

  pcp1: Cannot allocate 20481 bytes of memory: Cannot allocate memory

I have over 8GB free, so I'm confused.  Is it possible to use less memory?

**Comment by TLINDEN** [comment]
Hi,
you're right, it doesn't free memory somewhere and therefore during decryption uses more and more of it. I'll look into it.


- Tom

**Comment by TLINDEN** [comment]
Ok, try latest master. Shouldn't happen anymore. At least:

```
% ./vg.sh src/pcp1 --decrypt -O /dev/null -I x -x a
==51397== Memcheck, a memory error detector
==51397== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==51397== Using Valgrind-3.8.0 and LibVEX; rerun with -h for copyright info
==51397== Command: src/pcp1 --decrypt -O /dev/null -I x -x a
==51397==
Decrypted and Verified 66560 bytes successfully
==51397==
==51397== HEAP SUMMARY:
==51397==     in use at exit: 0 bytes in 0 blocks
==51397==   total heap usage: 99 allocs, 99 frees, 542,549 bytes allocated
==51397==
==51397== All heap blocks were freed -- no leaks are possible
==51397==
==51397== For counts of detected and suppressed errors, rerun with: -v
==51397== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

- Tom

**Comment by TLINDEN** [comment]
Any update on this?

**Comment by TLINDEN** [comment]
Well, I consider this fixed.

**Comment by Intensity** [comment]
It didn't seem to crash as it did before.
