### ISSUE TITLE
Mangled packet order, bailing out (got: 255, expected: 65535)!

### ISSUE THREAD

**Issue by Intensity** [TLINDEN/pcp#12]
I ran pcp1 without --sign and wrote a big file to an archive:

    $ cat bigfile | pcp1 --verbose  --encrypt --add-myself > out.pcp1

But then upon decrypt I got an error:

    $ cat out.pcp1 | pcp1 --verbose --decrypt | md5sum
    Mangled packet order, bailing out (got: 255, expected: 65535)!

This occurred pretty early on.  I'm writing a brief report here because I'm wondering how I might best debug this here.

**Comment by TLINDEN** [comment]
fixed in latest commit. Thanks for reporting, this one was too bad (comparision with < instead of <=).

Thanks,
Tom
