### ISSUE TITLE
compilation error for pcp-0.3.0.tar.gz

### ISSUE THREAD

**Issue by bodemann** [TLINDEN/pcp#19]
Compiling pcp-0.3.0.tar.gz gives the following error message on Ubuntu 16.04

context.c: In function 'ptx_new':
context.c:46:3: error: ignoring return value of 'sodium_init', declared with attribute warn_unused_result [-Werror=unused-result]
   sodium_init();

**Comment by TLINDEN** [comment]
Has been fixed a long time ago. Please try current git version:
```
git clone https://github.com/TLINDEN/pcp.git
cd pcp
./autogen.sh
./configure.sh
make
sudo make install
```

**Comment by bodemann** [comment]
Thank you for the quick answer. I did a ./configure && make check which results in:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -g -O2 -Werror -Wextra -Wall -g -DDEBUG -O2 -MT zmq_z85.lo -MD -MP -MF .deps/zmq_z85.Tpo -c zmq_z85.c  -fPIC -DPIC -o .libs/zmq_z85.o
zmq_z85.c: In function ‘zmq_z85_encode’:
zmq_z85.c:55:3: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
   if (size % 4 != 0)
   ^~
zmq_z85.c:58:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
     unsigned int char_nbr = 0;
     ^~~~~~~~
zmq_z85.c: At top level:
zmq_z85.c:111:1: fatal error: opening dependency file .deps/zmq_z85.Tpo: Permission denied
 }
 ^
cc1: all warnings being treated as errors
compilation terminated.
make[1]: *** [Makefile:487: zmq_z85.lo] Error 1

make alone leads to the same result, as expected. Any ideas?

**Comment by TLINDEN** [comment]
Hm, invalid indentation, strange. Fixed it in https://github.com/TLINDEN/pcp/commit/2ad190e9218a57b87c5fcfbce2ab6a09c1d98a1d, try `git pull && make`.
