### ISSUE TITLE
Batch creation of keypair

### ISSUE THREAD

**Issue by neuhaus** [TLINDEN/pcp#20]
I'd like to create a keypair from a script without user input. I also don't require a passphrase really.

Is this possible right now or could it be added?

I would also need to be able to extract the pub key from a script without user input.

The idea is to use pcp1 instead of openssl for [NX crypto photography](https://sites.google.com/site/nxcryptophotography/).

**Comment by TLINDEN** [comment]
Take a look at the unittests, there are some examples for this. However, I urge you **not** to do this and stick with openssl. PCP is not intended for production, it would create a false sense of security.
