### ISSUE TITLE
Compile Failure on SmarOS (Solaris)

### ISSUE THREAD

**Issue by sm-tradeboox** [TLINDEN/pcp#6]
Compilation failing on SmartOS.

Complete log:

[admin@services ~/pcp/pcp-0.2.4]$ ./configure --prefix='/opt/usr'
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /opt/local/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-pc-solaris2.11
checking host system type... x86_64-pc-solaris2.11
checking how to print strings... print -r
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /opt/local/bin/sed
checking for grep that handles long lines and -e... /opt/local/bin/grep
checking for egrep... /opt/local/bin/grep -E
checking for fgrep... /opt/local/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /opt/local/bin/nm -B
checking the name lister (/opt/local/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786240
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-solaris2.11 file names to x86_64-pc-solaris2.11 format... func_convert_file_noop
checking how to convert x86_64-pc-solaris2.11 file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... print -r --
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /opt/local/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... solaris2.11 ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -64
checking if the linker (/usr/bin/ld -64) is GNU ld... no
checking whether the g++ linker (/usr/bin/ld -64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -64) supports shared libraries... yes
checking dynamic linker characteristics... solaris2.11 ld.so
checking how to hardcode library paths into programs... immediate
checking how to run the C++ preprocessor... g++ -E
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking whether gcc and cc understand -c and -o together... yes
checking for a sed that does not truncate output... (cached) /opt/local/bin/sed
checking for gawk... (cached) gawk
checking for ANSI C header files... (cached) yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking err.h usability... yes
checking err.h presence... yes
checking for err.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking endian.h usability... no
checking endian.h presence... no
checking for endian.h... no
checking sys/endian.h usability... no
checking sys/endian.h presence... no
checking for sys/endian.h... no
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking for size_t... yes
checking for arc4random_buf... no
checking for arc4random... no
checking for fread... yes
checking for fopen... yes
checking for free... yes
checking for fwrite... yes
checking for fseek... yes
checking for ftruncate... yes
checking for fprintf... yes
checking for isatty... yes
checking for malloc... yes
checking for memset... yes
checking for memcpy... yes
checking for perror... yes
checking for strnlen... yes
checking for strnstr... yes
checking for strlen... yes
checking for strtol... yes
checking for sizeof... no
checking for tcgetattr... yes
checking for umask... yes
checking for towlower... yes
checking for getopt_long... yes
checking for vasprintf... yes
checking for be32toh... yes
checking for htobe32... yes
checking whether be64enc is declared... no
checking for posix_memalign... yes
checking compiler and flags for sanity... yes
checking pkg-config for libsodium... no
checking for sodium_init in -lsodium... yes
checking is libsodium compiled correctly... yes
checking are we on a big endian system... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating libpcp/Makefile
config.status: creating libpcp/scrypt/Makefile
config.status: creating src/Makefile
config.status: creating man/Makefile
config.status: creating tests/Makefile
config.status: creating libpcp/libpcp1.pc
config.status: creating bindings/cpp/Makefile
config.status: creating bindings/py/Makefile
config.status: creating include/pcp/config.h
config.status: executing depfiles commands
config.status: executing libtool commands

    Build configured for pcp 0.2.4:
        CC:                     gcc
        CFLAGS:                  -Werror -Wextra -Wall -g -O2
        CXX:                    g++
        CXXFLAGS:                -Werror -Wextra -Wall -g -O2
        LDFLAGS:                -L/opt/usr/lib -L/opt/local/lib -L/usr/local/lib -L/usr/lib
        LIBS:                   -lsodium 
        debug:                  yes
        optimize:               -O2

        prefix:                 /opt/usr
        libdir:                 ${exec_prefix}/lib
        includedir:             ${prefix}/include

        target platform:        x86_64-pc-solaris2.11
        big endian cpu:         no

        build python binding:   no
        build c++ binding:      yes

    Type 'make' to build, 'make install' to install.
    To execute unit tests, type 'make test'.

[admin@services ~/pcp/pcp-0.2.4]$ make
Making all in include
make[1]: Entering directory '/home/admin/pcp/pcp-0.2.4/include'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/admin/pcp/pcp-0.2.4/include'
Making all in libpcp
make[1]: Entering directory '/home/admin/pcp/pcp-0.2.4/libpcp'
Making all in scrypt
make[2]: Entering directory '/home/admin/pcp/pcp-0.2.4/libpcp/scrypt'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/admin/pcp/pcp-0.2.4/libpcp/scrypt'
make[2]: Entering directory '/home/admin/pcp/pcp-0.2.4/libpcp'
/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include/pcp    -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT platform.lo -MD -MP -MF .deps/platform.Tpo -c -o platform.lo platform.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT platform.lo -MD -MP -MF .deps/platform.Tpo -c platform.c  -fPIC -DPIC -o .libs/platform.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT platform.lo -MD -MP -MF .deps/platform.Tpo -c platform.c -o platform.o >/dev/null 2>&1
mv -f .deps/platform.Tpo .deps/platform.Plo
/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include/pcp    -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT mac.lo -MD -MP -MF .deps/mac.Tpo -c -o mac.lo mac.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT mac.lo -MD -MP -MF .deps/mac.Tpo -c mac.c  -fPIC -DPIC -o .libs/mac.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT mac.lo -MD -MP -MF .deps/mac.Tpo -c mac.c -o mac.o >/dev/null 2>&1
mv -f .deps/mac.Tpo .deps/mac.Plo
/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include/pcp    -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT mem.lo -MD -MP -MF .deps/mem.Tpo -c -o mem.lo mem.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT mem.lo -MD -MP -MF .deps/mem.Tpo -c mem.c  -fPIC -DPIC -o .libs/mem.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT mem.lo -MD -MP -MF .deps/mem.Tpo -c mem.c -o mem.o >/dev/null 2>&1
mv -f .deps/mem.Tpo .deps/mem.Plo
/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include/pcp    -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT pad.lo -MD -MP -MF .deps/pad.Tpo -c -o pad.lo pad.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT pad.lo -MD -MP -MF .deps/pad.Tpo -c pad.c  -fPIC -DPIC -o .libs/pad.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT pad.lo -MD -MP -MF .deps/pad.Tpo -c pad.c -o pad.o >/dev/null 2>&1
mv -f .deps/pad.Tpo .deps/pad.Plo
/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include/pcp    -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT version.lo -MD -MP -MF .deps/version.Tpo -c -o version.lo version.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT version.lo -MD -MP -MF .deps/version.Tpo -c version.c  -fPIC -DPIC -o .libs/version.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT version.lo -MD -MP -MF .deps/version.Tpo -c version.c -o version.o >/dev/null 2>&1
mv -f .deps/version.Tpo .deps/version.Plo
/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include/pcp    -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT context.lo -MD -MP -MF .deps/context.Tpo -c -o context.lo context.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT context.lo -MD -MP -MF .deps/context.Tpo -c context.c  -fPIC -DPIC -o .libs/context.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT context.lo -MD -MP -MF .deps/context.Tpo -c context.c -o context.o >/dev/null 2>&1
mv -f .deps/context.Tpo .deps/context.Plo
/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include/pcp    -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT z85.lo -MD -MP -MF .deps/z85.Tpo -c -o z85.lo z85.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT z85.lo -MD -MP -MF .deps/z85.Tpo -c z85.c  -fPIC -DPIC -o .libs/z85.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT z85.lo -MD -MP -MF .deps/z85.Tpo -c z85.c -o z85.o >/dev/null 2>&1
mv -f .deps/z85.Tpo .deps/z85.Plo
/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include/pcp    -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT zmq_z85.lo -MD -MP -MF .deps/zmq_z85.Tpo -c -o zmq_z85.lo zmq_z85.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT zmq_z85.lo -MD -MP -MF .deps/zmq_z85.Tpo -c zmq_z85.c  -fPIC -DPIC -o .libs/zmq_z85.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT zmq_z85.lo -MD -MP -MF .deps/zmq_z85.Tpo -c zmq_z85.c -o zmq_z85.o >/dev/null 2>&1
mv -f .deps/zmq_z85.Tpo .deps/zmq_z85.Plo
/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include/pcp    -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT key.lo -MD -MP -MF .deps/key.Tpo -c -o key.lo key.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -O2 -MT key.lo -MD -MP -MF .deps/key.Tpo -c key.c  -fPIC -DPIC -o .libs/key.o
In file included from ../include/pcp/key.h:32:0,
                 from key.c:23:
key.c: In function 'key2be':
key.c:295:18: note: in expansion of macro 'htobe32'
     k->serial  = htobe32(k->serial);
                  ^
../include/pcp/platform.h:63:27: error: 'u_int64_t' undeclared (first use in this function)
 #     define htobe64(x) ((u_int64_t)htonl((u_int64_t)(x)))
                           ^
key.c:296:18: note: in expansion of macro 'htobe64'
     k->ctime   = htobe64(k->ctime);
                  ^
../include/pcp/platform.h:63:37: error: expected ')' before 'htonl'
 #     define htobe64(x) ((u_int64_t)htonl((u_int64_t)(x)))
                                     ^
key.c:296:18: note: in expansion of macro 'htobe64'
     k->ctime   = htobe64(k->ctime);
                  ^
key.c: In function 'pubkey2native':
../include/pcp/platform.h:60:27: error: 'u_int32_t' undeclared (first use in this function)
 #     define be32toh(x) ((u_int32_t)ntohl((u_int32_t)(x)))
                           ^
key.c:306:16: note: in expansion of macro 'be32toh'
   k->version = be32toh(k->version);
                ^
../include/pcp/platform.h:60:37: error: expected ')' before 'ntohl'
 #     define be32toh(x) ((u_int32_t)ntohl((u_int32_t)(x)))
                                     ^
key.c:306:16: note: in expansion of macro 'be32toh'
   k->version = be32toh(k->version);
                ^
../include/pcp/platform.h:60:37: error: expected ')' before 'ntohl'
 #     define be32toh(x) ((u_int32_t)ntohl((u_int32_t)(x)))
                                     ^
key.c:307:16: note: in expansion of macro 'be32toh'
   k->serial  = be32toh(k->serial);
                ^
../include/pcp/platform.h:62:27: error: 'u_int64_t' undeclared (first use in this function)
 #     define be64toh(x) ((u_int64_t)ntohl((u_int64_t)(x)))
                           ^
key.c:308:16: note: in expansion of macro 'be64toh'
   k->ctime   = be64toh(k->ctime);
                ^
../include/pcp/platform.h:62:37: error: expected ')' before 'ntohl'
 #     define be64toh(x) ((u_int64_t)ntohl((u_int64_t)(x)))
                                     ^
key.c:308:16: note: in expansion of macro 'be64toh'
   k->ctime   = be64toh(k->ctime);
                ^
Makefile:447: recipe for target 'key.lo' failed
make[2]: *** [key.lo] Error 1
make[2]: Leaving directory '/home/admin/pcp/pcp-0.2.4/libpcp'
Makefile:522: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/admin/pcp/pcp-0.2.4/libpcp'
Makefile:354: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by TLINDEN** [comment]
Could you please try again with latest master? I had a typo in platform.h.

**Comment by TLINDEN** [comment]
Could you please try again with latest master? I had a typo in platform.h.

**Comment by sm-tradeboox** [comment]
Thanks. This issue seems to have been resolved. 

Now there's another, I'll post another ticket for it and keep the logs short. If you want the complete log, please let me know.
