### ISSUE TITLE
Error in crypto.c (Solaris based platform)

### ISSUE THREAD

**Issue by sm-tradeboox** [TLINDEN/pcp#7]
Compile failing with the following log. I can provide complete logs if you need these. Thanks. Sam

/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include/pcp    -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -DDEBUG -O2 -MT crypto.lo -MD -MP -MF .deps/crypto.Tpo -c -o crypto.lo crypto.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include/pcp -I../include/pcp -Iscrypt/crypto -Iscrypt/util -Werror -Wextra -Wall -g -DDEBUG -O2 -MT crypto.lo -MD -MP -MF .deps/crypto.Tpo -c crypto.c  -fPIC -DPIC -o .libs/crypto.o
crypto.c: In function '_get_nonce_ctr':
crypto.c:714:3: error: 'ctr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   return ctr;
   ^
cc1: all warnings being treated as errors
Makefile:522: recipe for target 'crypto.lo' failed
make[2]: *** [crypto.lo] Error 1
make[2]: Leaving directory '/home/admin/pcp/libpcp'
Makefile:597: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/admin/pcp/libpcp'
Makefile:416: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

**Comment by sm-tradeboox** [comment]
Could this below be related to the error?

$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config --force -I config
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `config'.
libtoolize: copying file `config/libtool.m4'
libtoolize: copying file `config/ltoptions.m4'
libtoolize: copying file `config/ltsugar.m4'
libtoolize: copying file `config/ltversion.m4'
libtoolize: copying file `config/lt~obsolete.m4'
autoreconf: running: /opt/local/bin/autoconf --include=config --force
autoreconf: running: /opt/local/bin/autoheader --include=config --force
autoreconf: running: automake --add-missing --copy --force-missing
libpcp/Makefile.am:29: warning: source file 'scrypt/crypto/sha256.c' is in a subdirectory,
libpcp/Makefile.am:29: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
libpcp/Makefile.am:29: warning: source file 'scrypt/crypto/crypto_scrypt-nosse.c' is in a subdirectory,
libpcp/Makefile.am:29: but option 'subdir-objects' is disabled
tests/Makefile.am:59: warning: source file '../src/compat_getopt.c' is in a subdirectory,
tests/Makefile.am:59: but option 'subdir-objects' is disabled
autoreconf: Leaving directory `.'

**Comment by TLINDEN** [comment]
Should work now, could you try again please with latest master?


thx,
Tom

**Comment by sm-tradeboox** [comment]
make install successful. Make check failing, posting another issue.

**Comment by TLINDEN** [comment]
ok, so I close this one
