### ISSUE TITLE
File signature check working?

### ISSUE THREAD

**Issue by sm-tradeboox** [TLINDEN/pcp#9]
Signature check does not seem to be working, or I'm doing something wrong?

	# Simple file, contents listed
	[admin@services ~]$ cat gcc-env
	export PATH=/opt/local/gcc49/bin:$PATH
	export CPATH=/opt/usr/include:/opt/local/include:/usr/local/include:/usr/include
	export LIBRARY_PATH=/opt/usr/lib:/opt/local/lib:/usr/local/lib:/usr/lib
	export LD_LIBRARY_PATH=$LIBRARY_PATH
	export CFLAGS='-I/opt/usr/include -I/opt/local/include -I/usr/local/include -I/usr/include'
	export LDFLAGS='-L/opt/usr/lib -L/opt/local/lib -L/usr/local/lib -L/usr/lib'

	[admin@services ~]$ pcp1 -g -f gcc-env.sign0 -I gcc-env
	Enter passphrase to decrypt your secret key: 
	Signed 399 bytes successfully

	[admin@services ~]$ pcp1 -g -z -f gcc-env.signz -I gcc-env
	Enter passphrase to decrypt your secret key: 
	Signed 399 bytes successfully

	[admin@services ~]$ diff gcc-env.sign?
	5c5
	< &R)nX6EwKto*8D7Pb3NuAp8
	---
	> &R)nX6EwKto*8D7Pb3AkO:S

	[admin@services ~]$ cat gcc-env.sign?
	----- BEGIN ED25519 SIGNATURE -----
	Version: PCP v0.2.5
	DVieI6&Fm}bc>{wD<-<LBXS0@z/S{Aa9aJQ(@[6OHdGaF?])Dj{N0/xZ1-^f/qfdekh!l&S
	hOTyaocl.DfJIQs#:8r@]#()93g8?.V9hb-YyXmwHe#cC9(d59D-?xZ4^D29+?NW=nYMlWo
	&R)nX6EwKto*8D7Pb3NuAp8
	----- END ED25519 SIGNATURE -----
	----- BEGIN ED25519 SIGNATURE -----
	Version: PCP v0.2.5
	DVieI6&Fm}bc>{wD<-<LBXS0@z/S{Aa9aJQ(@[6OHdGaF?])Dj{N0/xZ1-^f/qfdekh!l&S
	hOTyaocl.DfJIQs#:8r@]#()93g8?.V9hb-YyXmwHe#cC9(d59D-?xZ4^D29+?NW=nYMlWo
	&R)nX6EwKto*8D7Pb3AkO:S
	----- END ED25519 SIGNATURE -----

	[admin@services ~]$ pcp1 -c -f gcc-env.sign0 -I gcc-env
	[admin@services ~]$ pcp1 -c -z -f gcc-env.signz -I gcc-env

	# similar output (or lack of) for any random file 
	[admin@services ~]$ pcp1 -c -z -f gcc-env.signz -I master.zip 
	[admin@services ~]$ ll master.zip 
	-rw-r--r-- 1 admin staff 2109545 Mar 30 17:46 master.zip

	# List of keys
	[admin@services ~]$ pcp1 -l
	Key ID               Type             Creation Time        Owner
	0xAF9171F9E6A45209   primary secret   2015-03-31T21:12:16  samir <sam@abc>
	0x08B6F40EA6D3B0E9   secret           2015-03-31T21:34:34  smi <smi@def>

**Comment by TLINDEN** [comment]
Well, no :) Basically you did everything right. But I think I forgot to implement the case when someone wants to verify a signature created by himself (which is what you did). If you use another user (or use -V), import the public key and verify the signature, everything works as expected.

I'll look at it. Thanks for finding it!


- Tom
